@server=http://localhost:4004
@username=alice
@password=


### assignUsersToGroup
# @name assignUsersToGroup_POST
POST {{server}}/odata/v4/SCIMService/assignUsersToGroup
Content-Type: application/json
# Authorization: Basic {{username}}:{{password}}

{
  "groupId": "ExampleGroup",
  "emails": [
    "john.smith@example.com"
  ]
}


### assignGroupsToUser
# @name assignGroupsToUser_POST
POST {{server}}/odata/v4/SCIMService/assignGroupsToUser
Content-Type: application/json
# Authorization: Basic {{username}}:{{password}}

{
  "email": "john.smith@example.com",
  "groupsNames": [
    "ExampleGroup",
    "Group2"
  ]
}


### getGroupId
# @name getGroupId_POST
POST {{server}}/odata/v4/SCIMService/getGroupId
Content-Type: application/json
# Authorization: Basic {{username}}:{{password}}

{
  "groupName": "Group2"
}


### getAllUsers
# @name getAllUsers_POST
POST {{server}}/odata/v4/SCIMService/getAllUsers
Content-Type: application/json
# Authorization: Basic {{username}}:{{password}}

{}


### getUserUuidByEmail
# @name getUserUuidByEmail_POST
POST {{server}}/odata/v4/SCIMService/getUserUuidByEmail
Content-Type: application/json
# Authorization: Basic {{username}}:{{password}}

{
  "email": "john.smith@example.com"
}


### revokeGroupsFromUser
# @name revokeGroupsFromUser_POST
POST {{server}}/odata/v4/SCIMService/revokeGroupsFromUser
Content-Type: application/json
# Authorization: Basic {{username}}:{{password}}

{
  "email": "john.smith@example.com",
  "groupsNames": [
    "ExampleGroup",
    "Group2"
  ]
}

### createSimpleUser - Minimal required fields for testing
# @name createSimpleUser_POST
POST {{server}}/odata/v4/SCIMService/createSimpleUser
Content-Type: application/json
# Authorization: Basic {{username}}:{{password}}

{
  "email": "jane.doe@example.com",
  "firstName": "Jane",
  "lastName": "Doe",
  "password": "TempPassword123!"
}


### handleChatbotInput
# @name handleChatbotInput_POST
POST {{server}}/odata/v4/ChatbotService/handleChatbotInput
Content-Type: application/json

{
  "input": "Add jane.doe@example.com to Group2"
}
