@server=http://localhost:4004
@username=alice
@password=


### assignUsersToGroup
# @name assignUsersToGroup_POST
POST {{server}}/odata/v4/SCIMService/assignUsersToGroup
Content-Type: application/json
#Authorization: Basic {{username}}:{{password}}

{
  "groupId": "98829775-0a4e-4768-80fa-191e5dbf6bf5",
  "emails": [
    "john.smith@example.com"
  ]
}


### assignGroupsToUser
# @name assignGroupsToUser_POST
POST {{server}}/odata/v4/SCIMService/assignGroupsToUser
Content-Type: application/json
#Authorization: Basic {{username}}:{{password}}

{
  "email": "john.smith@example.com",
  "groupsNames": [
    "Administrators"
  ]
}


### getGroupId
# @name getGroupId_POST
POST {{server}}/odata/v4/SCIMService/getGroupId
Content-Type: application/json
#Authorization: Basic {{username}}:{{password}}

{
  "groupName": "Administrators"
}


### getAllUsers
# @name getAllUsers_POST
POST {{server}}/odata/v4/SCIMService/getAllUsers
Content-Type: application/json
#Authorization: Basic {{username}}:{{password}}

{}


### getUserUuidByEmail
# @name getUserUuidByEmail_POST
POST {{server}}/odata/v4/SCIMService/getUserUuidByEmail
Content-Type: application/json
#Authorization: Basic {{username}}:{{password}}

{
  "email": "john.smith@example.com"
}
